unet:
  _target_: src.model.ldm.unet.UNetModel
  image_size: 32
  in_channels: 13
  out_channels: 4
  model_channels: 320
  attention_resolutions: [ 4, 2, 1 ]
  num_res_blocks: 2
  channel_mult: [ 1, 2, 4, 4 ]
  num_heads: 8
  use_spatial_transformer: True
  transformer_depth: 1
  context_dim: 768
  use_checkpoint: True
  legacy: False
  add_conv_in_front_of_unet: False
vae:
  _target_: diffusers.models.AutoencoderKL.from_pretrained
  pretrained_model_name_or_path: "stabilityai/sd-vae-ft-mse"
reface:
  _target_: src.model.REFace
  landmark_predictor_path: "data/checkpoints/shape_predictor_68_face_landmarks.dat"
  arcface_path: "data/checkpoints/model_ir_se50.pth"
  ddim_steps: 5
sd_ckpt: "data/checkpoints/sd-v1-4-modified-13channel.ckpt"